### ISSUE TITLE
더 좋은 가독성을 위한 개선요청

### ISSUE THREAD

**Issue by jyeonjyan** [yoosion030/Front_Interview#1]
![image](https://user-images.githubusercontent.com/67095821/132099653-8512edf9-9876-41e7-89b5-2d784e9b0481.png)

첨부한 사진처럼 url이 그대로 노출 돼 있는 부분이 있는데, 
마크다운은 아래 형식과 같은 linking 문법을 지원하니 교정하면 더 깔끔할 듯!

```
[ex.벨로그-이건뭔가요?](url)
```

**Comment by yoosion030** [comment]
선배 말대로 저렇게 하면 가독성이 훨씬 좋아질 것 같아요 !!  저렇게 고쳐보도록 할게요 😃 👍
